import type { InventoryItem } from "@/lib/types/inventory"

export const inventory: InventoryItem[] = [
  {
    id: "inv-001",
    itemType: "FIREARM",
    status: "AVAILABLE",
    name: "JFC-15 MOD 1",
    description: "Semi-automatic AR-platform rifle chambered in 5.56 NATO. Features M-LOK handguard and mil-spec trigger group.",
    manufacturer: "Jackson Firearm Co",
    brand: "JFC",
    model: "JFC-15 MOD 1",
    sku: "JFC-AR15-M1",
    upc: "810000000001",
    price: 1299.00,
    cost: 780.00,
    quantity: 3,
    taxMode: "DEFAULT",
    location: "RACK-A1",
    sourceSystem: "MANUAL",
    firearm: {
      serialNumber: "JFC15001",
      caliber: "5.56 NATO",
      action: "Semi-Auto",
      barrelLength: "16\"",
      capacity: "30+1",
      finish: "Matte Black",
      firearmType: "RIFLE",
      requiresFflTransfer: true,
    },
    createdAt: "2025-09-15T00:00:00Z",
    updatedAt: "2025-11-01T00:00:00Z",
  },
  {
    id: "inv-002",
    itemType: "FIREARM",
    status: "RESERVED",
    name: "SENTINEL-9 ELITE",
    description: "Compact 9mm pistol with tritium night sights and extended magazine well. Layaway in progress.",
    manufacturer: "Sentinel Arms",
    brand: "Sentinel",
    model: "Sentinel-9 Elite",
    sku: "SA-9E-001",
    upc: "810000000002",
    price: 849.00,
    cost: 510.00,
    quantity: 1,
    taxMode: "DEFAULT",
    location: "CASE-B2",
    sourceSystem: "ROCPAY",
    sourceId: "RP-88432",
    firearm: {
      serialNumber: "SA9E00422",
      caliber: "9mm Luger",
      action: "Semi-Auto",
      barrelLength: "3.9\"",
      capacity: "15+1",
      finish: "Stainless",
      firearmType: "HANDGUN",
      requiresFflTransfer: true,
    },
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2025-11-15T00:00:00Z",
  },
  {
    id: "inv-003",
    itemType: "FIREARM",
    status: "DRAFT",
    name: "JFC-308 PRECISION",
    description: "Heavy-barrel precision rifle in .308 WIN. Pending final inspection before listing.",
    manufacturer: "Jackson Firearm Co",
    brand: "JFC",
    model: "JFC-308 Precision",
    sku: "JFC-308-P1",
    price: 2199.00,
    cost: 1340.00,
    quantity: 0,
    taxMode: "DEFAULT",
    location: "SERVICE",
    sourceSystem: "MANUAL",
    firearm: {
      serialNumber: "JFC308001",
      caliber: ".308 WIN",
      action: "Bolt-Action",
      barrelLength: "24\"",
      capacity: "5+1",
      finish: "FDE Cerakote",
      firearmType: "RIFLE",
      requiresFflTransfer: true,
    },
    createdAt: "2025-11-20T00:00:00Z",
    updatedAt: "2025-11-20T00:00:00Z",
  },
  {
    id: "inv-004",
    itemType: "FIREARM",
    status: "AVAILABLE",
    name: "ATLAS 12 GAUGE",
    description: "Pump-action 12-gauge shotgun with 18.5\" barrel. Home defense configuration with ghost ring sights.",
    manufacturer: "Atlas Defense",
    brand: "Atlas",
    model: "Atlas 12",
    sku: "ATL-12G-001",
    upc: "810000000004",
    price: 749.00,
    cost: 440.00,
    quantity: 2,
    taxMode: "DEFAULT",
    location: "RACK-A3",
    sourceSystem: "FFLSAFE",
    sourceId: "FFL-20045",
    firearm: {
      serialNumber: "ATL12G8811",
      gauge: "12 Gauge",
      action: "Pump",
      barrelLength: "18.5\"",
      capacity: "6+1",
      finish: "Matte Black",
      firearmType: "SHOTGUN",
      requiresFflTransfer: true,
    },
    createdAt: "2025-08-10T00:00:00Z",
    updatedAt: "2025-10-05T00:00:00Z",
  },
  {
    id: "inv-005",
    itemType: "FIREARM",
    status: "SOLD",
    name: "COMPACT CARRY 45",
    description: "Slim-profile .45 ACP carry pistol. Sold via RocPay layaway — transfer complete.",
    manufacturer: "Compact Defense",
    brand: "Compact",
    model: "Carry 45",
    sku: "CD-45-001",
    upc: "810000000005",
    price: 699.00,
    cost: 415.00,
    quantity: 0,
    taxMode: "DEFAULT",
    sourceSystem: "ROCPAY",
    sourceId: "RP-77201",
    firearm: {
      serialNumber: "CD45001837",
      caliber: ".45 ACP",
      action: "Semi-Auto",
      barrelLength: "3.3\"",
      capacity: "7+1",
      finish: "Black Nitride",
      firearmType: "HANDGUN",
      requiresFflTransfer: true,
    },
    createdAt: "2025-07-01T00:00:00Z",
    updatedAt: "2025-10-30T00:00:00Z",
  },
  {
    id: "inv-006",
    itemType: "PART",
    status: "AVAILABLE",
    name: "TITANIUM BCG",
    description: "Full-auto rated titanium bolt carrier group with nickel boron coating. Fits mil-spec AR-15 lower.",
    manufacturer: "Apex Parts",
    brand: "Apex",
    model: "Ti-BCG",
    sku: "AP-TIBCG-01",
    upc: "810000000006",
    price: 219.00,
    cost: 130.00,
    quantity: 12,
    taxMode: "DEFAULT",
    location: "SHELF-C1",
    sourceSystem: "MANUAL",
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-11-01T00:00:00Z",
  },
  {
    id: "inv-007",
    itemType: "PART",
    status: "AVAILABLE",
    name: "M-LOK HANDGUARD 15\"",
    description: "Free-float M-LOK compatible aluminum handguard, 15 inch. Type III hard anodized black.",
    manufacturer: "Apex Parts",
    brand: "Apex",
    model: "ML-HG15",
    sku: "AP-MLHG15",
    upc: "810000000007",
    price: 179.00,
    cost: 98.00,
    quantity: 8,
    taxMode: "DEFAULT",
    location: "SHELF-C2",
    sourceSystem: "MANUAL",
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-11-01T00:00:00Z",
  },
  {
    id: "inv-008",
    itemType: "PART",
    status: "AVAILABLE",
    name: "MATCH TRIGGER GROUP",
    description: "Drop-in match trigger group with 3.5 lb pull weight. Compatible with standard AR-15 lowers.",
    manufacturer: "TriggerTech",
    brand: "TriggerTech",
    model: "Match AR",
    sku: "TT-MAR-001",
    upc: "810000000008",
    price: 159.00,
    cost: 88.00,
    quantity: 6,
    taxMode: "DEFAULT",
    location: "SHELF-C3",
    sourceSystem: "ROCPAY",
    sourceId: "RP-55100",
    createdAt: "2025-10-15T00:00:00Z",
    updatedAt: "2025-11-10T00:00:00Z",
  },
  {
    id: "inv-009",
    itemType: "PART",
    status: "ARCHIVED",
    name: "LEGACY MUZZLE COMP",
    description: "Discontinued 3-port compensator. No longer stocked — superseded by V2 model.",
    manufacturer: "Apex Parts",
    brand: "Apex",
    model: "Comp-V1",
    sku: "AP-COMP-V1",
    price: 59.00,
    cost: 28.00,
    quantity: 0,
    taxMode: "DEFAULT",
    sourceSystem: "MANUAL",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "inv-010",
    itemType: "ACCESSORY",
    status: "RESERVED",
    name: "RED DOT RDS-1",
    description: "2 MOA red dot sight with auto-brightness. 50,000 hour battery life. On hold for customer order.",
    manufacturer: "OpticsPro",
    brand: "OpticsPro",
    model: "RDS-1",
    sku: "OP-RDS1",
    upc: "810000000010",
    price: 249.00,
    cost: 148.00,
    quantity: 2,
    taxMode: "DEFAULT",
    location: "CASE-A1",
    sourceSystem: "FFLSAFE",
    sourceId: "FFL-30011",
    createdAt: "2025-10-20T00:00:00Z",
    updatedAt: "2025-11-18T00:00:00Z",
  },
  {
    id: "inv-011",
    itemType: "APPAREL",
    status: "AVAILABLE",
    name: "JFC LOGO TEE",
    description: "100% cotton short-sleeve tee with embossed JFC shield logo on chest. Pre-shrunk.",
    manufacturer: "Jackson Firearm Co",
    brand: "JFC",
    model: "Logo Tee",
    sku: "JFC-TEE-BLK",
    upc: "810000000011",
    price: 34.00,
    cost: 12.00,
    quantity: 48,
    taxMode: "DEFAULT",
    location: "MERCH-SHELF",
    sourceSystem: "MANUAL",
    apparel: {
      size: "S / M / L / XL / 2XL",
      color: "Black",
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-11-01T00:00:00Z",
  },
  {
    id: "inv-012",
    itemType: "APPAREL",
    status: "AVAILABLE",
    name: "RANGE HOODIE",
    description: "Heavyweight fleece pullover hoodie with kangaroo pocket and JFC wordmark across back.",
    manufacturer: "Jackson Firearm Co",
    brand: "JFC",
    model: "Range Hoodie",
    sku: "JFC-HOOD-OD",
    upc: "810000000012",
    price: 69.00,
    cost: 28.00,
    quantity: 20,
    taxMode: "DEFAULT",
    location: "MERCH-SHELF",
    sourceSystem: "MANUAL",
    apparel: {
      size: "M / L / XL / 2XL",
      color: "OD Green",
    },
    createdAt: "2025-08-15T00:00:00Z",
    updatedAt: "2025-11-01T00:00:00Z",
  },
  {
    id: "inv-013",
    itemType: "APPAREL",
    status: "DRAFT",
    name: "OPERATOR CAP",
    description: "Structured 6-panel cap with JFC shield patch. Awaiting size run confirmation before publishing.",
    manufacturer: "Jackson Firearm Co",
    brand: "JFC",
    model: "Operator Cap",
    sku: "JFC-CAP-TAN",
    price: 28.00,
    cost: 9.00,
    quantity: 0,
    taxMode: "DEFAULT",
    sourceSystem: "MANUAL",
    apparel: {
      size: "One Size",
      color: "Tan",
    },
    createdAt: "2025-11-10T00:00:00Z",
    updatedAt: "2025-11-10T00:00:00Z",
  },
  {
    id: "inv-014",
    itemType: "APPAREL",
    status: "AVAILABLE",
    name: "TACTICAL RANGE BAG",
    description: "600D polyester range bag with pistol rug compartment, 4 mag pouches, and padded dividers.",
    manufacturer: "FieldGear Co",
    brand: "FieldGear",
    model: "Tac-Range Pro",
    sku: "FG-TRP-BLK",
    upc: "810000000014",
    price: 89.00,
    cost: 44.00,
    quantity: 7,
    taxMode: "DEFAULT",
    location: "MERCH-SHELF",
    sourceSystem: "ROCPAY",
    sourceId: "RP-44800",
    apparel: {
      size: "One Size",
      color: "Black",
    },
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2025-11-05T00:00:00Z",
  },
]
